### ISSUE TITLE
Bug bei Fenstervergrößerung

### ISSUE THREAD

**Issue by Wor0r** [ts12345/vier_gewinnt#49]
Wenn man das Spielfenster vergrößert kann man außerhalb klicken...

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 10
        at SPIELFELD.freiesFeld(SPIELFELD.java:70)
        at SPIELFELD.spielSteinSetzen(SPIELFELD.java:33)
        at CONTROLLER.spielsteinSetzen(CONTROLLER.java:156)
        at CONTROLLER.spielStarten(CONTROLLER.java:106)
        at OBERCONTROLLER.<init>(OBERCONTROLLER.java:47)
        at OBERCONTROLLER.main(OBERCONTROLLER.java:11)

**Comment by SFr682k** [comment]
Exception terminated >:)
